# /admin/config.yml
backend:
  name: github
  repo: posel4/posel4.github.io
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

backend:
  name: github
  repo: posel4/posel4.github.io
  branch: main
  auth_scope: repo
  base_url: https://api.netlify.com
  site_domain: posel4.github.io
  auth_endpoint: https://api.netlify.com/auth
  client_id: Ov23lic5NNL2uiUB5ocP
